### ISSUE TITLE
Android installation with RN 0.67.3

### ISSUE THREAD

**Issue by Spoutnik97** [DataDog/dd-sdk-reactnative#158]
Hi, 
I am trying to install the DataDog React Native SDK for React Native 0.67.3, but  I have an issue for Android.

Remarque: I resolved an issue for iOS thanks to this issue : https://github.com/DataDog/dd-sdk-reactnative/issues/41

I have the following error message when I run "react-native run-android": 

```
e: /Users/me/bam/epsor/mobile/node_modules/@datadog/mobile-react-native/android/src/main/java/com/datadog/reactnative/DdTrace.kt: (36, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/me/.gradle/caches/transforms-3/2cb76cdf5bc583a7cdc4100935699356/transformed/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /Users/me/bam/epsor/mobile/node_modules/@datadog/mobile-react-native/android/src/main/java/com/datadog/reactnative/DdTrace.kt: (47, 9): Class 'com.datadog.android.bridge.DdTrace' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/me/.gradle/caches/transforms-3/93d0fb38abbe5cfcf24d5a23f1062fbd/transformed/jetified-dd-bridge-android-0.5.3-api.jar!/com/datadog/android/bridge/DdTrace.class
e: /Users/me/bam/epsor/mobile/node_modules/@datadog/mobile-react-native/android/src/main/java/com/datadog/reactnative/DdTrace.kt: (47, 24): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/me/.gradle/caches/transforms-3/2cb76cdf5bc583a7cdc4100935699356/transformed/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /Users/me/bam/epsor/mobile/node_modules/@datadog/mobile-react-native/android/src/main/java/com/datadog/reactnative/DdTrace.kt: (48, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/me/.gradle/caches/transforms-3/2cb76cdf5bc583a7cdc4100935699356/transformed/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datadog_mobile-react-native:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (/Users/me/bam/epsor/mobile/node_modules/execa/index.js:174:9)
    at /Users/me/bam/epsor/mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/me/bam/epsor/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/me/bam/epsor/mobile/node_modules/@react-native-community/cli/build/index.js:192:9)
```

It seems to be an error with the Kotlin version. Do you know how to fix this?

**Comment by Spoutnik97** [comment]
How do you advise me to do this?

I added this line `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"`in the `dependencies` in my build.gradle

Do you think it is ok?

**Comment by 0xnm** [comment]
@Spoutnik97 In your top-level `build.gradle` you need to specify the `kotlinVersion` in the `buildscript.ext` block:

```groovy
buildscript {
    ext {
        ...
        kotlinVersion = "1.5.31"
    }
    ...
}
```
