### ISSUE TITLE
Datadog.error causes crashes on android

### ISSUE THREAD

**Issue by frederikvanhevel** [DataDog/dd-sdk-reactnative#269]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Crashlytics reports lots of crashes on android when using the 'error' log function: ` datadog.error(error.message)`

Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.s.e, parameter message
       at com.datadog.reactnative.DdLogs.error(DdLogs.kt:68)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)

**Steps to reproduce the issue:**

**Describe what you expected:**

**Additional context**
    - Version of the SDK: 1.0.0

**Comment by louiszawadzki** [comment]
Hi @frederikvanhevel, thank you for reaching out!

This would likely be caused by calling `DdLogs.error` without specifying a message (or specifying `null` or `undefined` as message).
Could you review the instances where you call this method to see if there is any occurence of this?

Thanks a lot :)

**Comment by frederikvanhevel** [comment]
That makes sense, thanks!
