### ISSUE TITLE
Can't get this working with Expo

### ISSUE THREAD

**Issue by onlyanegg** [DataDog/dd-sdk-reactnative#271]
**Describe what happened**
I can't get the DataDog SDK working within my expo project. I'm getting a couple different errors. 

One at the `prebuild` stage

```
✖ Config sync failed
SyntaxError: [ios.entitlements]: withIosEntitlementsBaseMod: Expected "/*" or ";" but "e" found.
```

And another at the `run:ios` stage.

```
TypeError: null is not an object (evaluating '_foundation.DdSdk.initialize')
```

I created a new minimal expo project. At a high level, here's what I'm doing.

```
# Create new expo project
yarn create expo-app datadog-expo-issue
cd datadog-expo-issue/

# Install expo-datadog and dependencies
yarn expo install expo-dev-client expo-datadog @datadog/datadog-ci

# Export MARKETING_VERSION and DATADOG_API_KEY
cp ../template/.envrc .
direnv allow

# Add datadog configuration and initialize
cp ../template/App.js .

# $ git diff App.js
# diff --git a/App.js b/App.js
# index 09f879b..4c77950 100644
# --- a/App.js
# +++ b/App.js
# @@ -1,6 +1,19 @@
#  import { StatusBar } from 'expo-status-bar';
#  import { StyleSheet, Text, View } from 'react-native';
#
# +import { DdSdkReactNative, DdSdkReactNativeConfiguration } from "expo-datadog";
# +
# +const config = new DdSdkReactNativeConfiguration(
# +  "<CLIENT_TOKEN>",
# +  "local",
# +  "<APPLICATION_ID>",
# +  false, // track user interactions such as tapping on a button. You can use
# +  false, // track XHR resources.
# +  false // track errors.
# +);
# +
# +DdSdkReactNative.initialize(config);
# +
#  export default function App() {
#    return (
#      <View style={styles.container}>

# Prebuild

yarn expo prebuild

# yarn run v1.22.15
# datadog-expo-issue/node_modules/.bin/expo prebuild
#
# 📝  Android package Learn more: https://expo.fyi/android-package
#
# ✔ What would you like your Android package name to be? … datadogexpoissue
#
#
# 📝  iOS Bundle Identifier Learn more: https://expo.fyi/bundle-identifier
#
# ✔ What would you like your iOS bundle identifier to be? … datadogexpoissue
#
# ✔ Created native projects | gitignore skipped
# ✔ Added Metro config
# ✔ Updated package.json and added index.js entry point for iOS and Android
# › Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead
#
# › Installing using Yarn
# Using node to generate images. This is much slower than using native packages.
# › Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
#
# ✖ Config sync failed
# SyntaxError: [ios.entitlements]: withIosEntitlementsBaseMod: Expected "/*" or ";" but "e" found.
# SyntaxError: [ios.entitlements]: withIosEntitlementsBaseMod: Expected "/*" or ";" but "e" found.
#     at peg$buildStructuredError (datadog-expo-issue/node_modules/xcode/lib/parser/pbxproj.js:429:12)
#     at Object.peg$parse [as parse] (datadog-expo-issue/node_modules/xcode/lib/parser/pbxproj.js:1891:11)
#     at pbxProject.parseSync (datadog-expo-issue/node_modules/xcode/lib/pbxProject.js:63:24)
#     at getPbxproj (datadog-expo-issue/node_modules/@expo/config-plugins/build/ios/utils/Xcodeproj.js:404:11)
#     at ensureApplicationTargetEntitlementsFileConfigured (datadog-expo-issue/node_modules/@expo/config-plugins/build/ios/Entitlements.js:132:47)
#     at getFilePath (datadog-expo-issue/node_modules/@expo/config-plugins/build/plugins/withIosBaseMods.js:393:79)
#     at action (datadog-expo-issue/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:68:34)
#     at interceptingMod (datadog-expo-issue/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:27)
#     at evalModsAsync (datadog-expo-issue/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:256:31)
#     at async Object.compileModsAsync (datadog-expo-issue/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:160:10)
# error Command failed with exit code 1.
# info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

# Is the config plugin really necessary?
# Seems like it only uploads debug symbols and source maps
jq 'del(.expo.plugins)' app.json > app.json.new && mv app.json.new app.json
yarn expo prebuild --clean
yarn expo run:ios

# ...
# › Installing on iPhone 14 Pro Max
# › Opening on iPhone 14 Pro Max (datadogexpoissue)
# › Opening datadogexpoissue://expo-development-client/?url=http%3A%2F%2F192.168.0.73%3A8081 on iPhone 14 Pro Max
#
# › Logs for your project will appear below. Press Ctrl+C to exit.
# iOS Bundling complete 5760ms
#  WARN  Possible Unhandled Promise Rejection (id: 0):
# TypeError: null is not an object (evaluating '_foundation.DdSdk.initialize')
# @http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:120077:28
# tryCallTwo@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:30625:9
# doResolve@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:30789:25
# Promise@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:30648:14
# initialize@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:120036:27
# @http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:119572:43
# loadModuleImplementation@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:290:14
# @http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:1357:48
# loadModuleImplementation@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:290:14
# guardedLoadModule@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:163:47
# global code@http://192.168.0.73:8081/index.bundle?platform=ios&dev=true&hot=false:121704:4
# › Stopped server
# ✨  Done in 151.29s.
```

**Additional context**
```
$ yarn list --pattern expo-datadog
yarn list v1.22.15
└─ expo-datadog@45.0.0
✨  Done in 0.18s.
```

```
$ cat package.json
{
  "name": "datadog-expo-issue",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@datadog/datadog-ci": "^1.13.3",
    "expo": "~46.0.9",
    "expo-datadog": "^45.0.0",
    "expo-dev-client": "~1.2.1",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "expo-splash-screen": "~0.16.2",
    "react-dom": "18.0.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

**Comment by louiszawadzki** [comment]
Hi @onlyanegg, thanks for reaching out!

`expo-datadog` is not yet supporting Expo 46 - which includes a change in the iOS build phase where we upload js source maps to Datadog.

We're currently bringing support for Expo 46 - see https://github.com/DataDog/dd-sdk-reactnative/pull/272.

**Comment by onlyanegg** [comment]
Thanks for getting back to me @louiszawadzki !

When I downgrade expo to 45, I'm still getting that second error

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_foundation.DdSdk.initialize')]
```

Seems like there's nothing related to datadog within the Podfile.lock, and when I look at `NativeModules`, `DdSdk` is not defined.

**Comment by onlyanegg** [comment]
Figured it out. TLDR: Install `@datadog/mobile-react-native`

I was looking into [how native library linking works](https://github.com/react-native-community/cli/blob/main/docs/platforms.md#how-does-it-work) and saw this line

> At the startup, React Native CLI reads configuration from all dependencies listed in package.json and reduces them into a single configuration.

And realized that the Pod spec was in the `@datadog/mobile-react-native` package which wasn't getting read by react-native since it wasn't a direct dependency of my app.

I see that that's part of your PR.

Anyway, thanks again! I appreciate your prompt response. You can probably close this now :)

**Comment by erisvaldojunior** [comment]
I still face this issue on Expo 46, shouldn't it be fixed already?

prebuild / EAS Build:

✖ Config sync failed
SyntaxError: [ios.entitlements]: withIosEntitlementsBaseMod: Expected "/*" or ";" but "e" found.

**Comment by erisvaldojunior** [comment]
Fixed the build issue upgrading expo-datadog to 46.0.0
