### ISSUE TITLE
Android: trackFrustrations cannot be cast from String to Boolean

### ISSUE THREAD

**Issue by short-dsb** [DataDog/dd-sdk-reactnative#488]
**Describe what happened**

Android builds the app successfully with version 1.7.1, but this error is displayed when it’s launched:

> trackFrustrations cannot be cast from String to Boolean

Previous version 1.6.0 works as intended.

**Steps to reproduce the issue:**

1. Install `@datadog-mobile-react-native@1.7.1`
2. Build for Android
3. Launch app

**Describe what you expected:**

App should run without errors.

**Additional context**

-   Version of the SDK: 1.7.1
-   Version of React Native: 0.71.8

**Comment by louiszawadzki** [comment]
Hi @short-dsb, thanks for reaching out!

Unfortunately we're not able to reproduce your issue, could you share what configuration you are passing to the SDK to help us troubleshoot?


Thanks a lot!

**Comment by short-dsb** [comment]
Of course!

```
import {
  DdSdkReactNative,
  DdSdkReactNativeConfiguration,
  TrackingConsent,
} from '@datadog/mobile-react-native';
```

```
useEffect(() => {
  const enableDatadog = async () => {
    const config = new DdSdkReactNativeConfiguration(
      '<REDACTED>',
      'prod',
      '<REDACTED>',
      true, // track User interactions
      !__DEV__, // track XHR Resources
      !__DEV__, // track Errors
      TrackingConsent.GRANTED,
    );
    config.site = 'US';
    config.nativeCrashReportEnabled = true;
    config.sampleRate = 100;
    config.firstPartyHosts = ['myapp.com'];

    await DdSdkReactNative.initialize(config);
  };
  enableDatadog();
}, []);
```

Thanks for taking a look. 🙂

**Comment by louiszawadzki** [comment]
Hi @short-dsb,

Unfortunately we're not able to reproduce this issue on our end, could you help us by sending some additional logs?

From the error it looks as if the `trackFrustrations` configuration parameter was set to a string, but it's not set in your snippet and it is set to `true` (boolean) by default.

Could you add some logs at the following places in the SDK (should be in `node_modules/@datadog/mobile-react-native`): 

- in `src/DdSdkReactNative.tsx`, line 104 (after `DdSdkReactNative.buildConfiguration(configuration);`:

```js
console.log("dd js configuration", configuration)
```
- in `android/src/main/kotlin/com/datadog/reactnative/DdSdk.kt`, line 62 (first line of the `initialize` method):

```kotlin
Log.d("DD_CONFIG", configuration.toString())
```

You can then get this native log with `pidcat` (you can see our guide to seeing native logs here: https://docs.datadoghq.com/real_user_monitoring/reactnative/troubleshooting/#on-android).


Thanks a lot!

**Comment by short-dsb** [comment]
```
dd js configuration {"actionEventMapper": null, "additionalConfig": {"_dd.first_party_hosts": [[Object]], "_dd.native_interaction_tracking": false, "_dd.native_view_tracking": false, "_dd.sdk_version": "1.6.0", "_dd.source": "react-native"}, "applicationId": "<REDACTED>", "clientToken": "<REDACTED>", "env": "prod", "errorEventMapper": null, "firstPartyHosts": ["myapp.com"], "logEventMapper": null, "longTaskThresholdMs": 0, "nativeCrashReportEnabled": true, "nativeInteractionTracking": false, "nativeLongTaskThresholdMs": 200, "nativeViewTracking": false, "proxyConfig": undefined, "resourceEventMapper": null, "resourceTracingSamplingRate": 20, "sampleRate": 100, "serviceName": undefined, "sessionSamplingRate": 100, "site": "US", "telemetrySampleRate": 20, "trackErrors": false, "trackFrustrations": true, "trackInteractions": false, "trackResources": false, "trackingConsent": "granted", "verbosity": undefined, "vitalsUpdateFrequency": "AVERAGE"}
```

```
06-12 11:01:51.017 28614 28724 I ReactNativeJS: 'dd js configuration', { clientToken: '<READACTED>d',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   env: 'prod',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   applicationId: '<READACTED>',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   trackInteractions: false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   trackResources: false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   trackErrors: false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   trackingConsent: 'granted',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   nativeCrashReportEnabled: true,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   sessionSamplingRate: 100,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   resourceTracingSamplingRate: 20,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   site: 'US',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   verbosity: undefined,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   nativeViewTracking: false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   nativeInteractionTracking: false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   proxyConfig: undefined,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   serviceName: undefined,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   firstPartyHosts: [ 'myapp.com' ],
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   telemetrySampleRate: 20,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   nativeLongTaskThresholdMs: 200,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   longTaskThresholdMs: 0,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   vitalsUpdateFrequency: 'AVERAGE',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   trackFrustrations: true,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   logEventMapper: null,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   errorEventMapper: null,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   resourceEventMapper: null,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   actionEventMapper: null,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   additionalConfig:
06-12 11:01:51.017 28614 28724 I ReactNativeJS:    { '_dd.source': 'react-native',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:      '_dd.sdk_version': '1.6.0',
06-12 11:01:51.017 28614 28724 I ReactNativeJS:      '_dd.native_view_tracking': false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:      '_dd.native_interaction_tracking': false,
06-12 11:01:51.017 28614 28724 I ReactNativeJS:      '_dd.first_party_hosts': [ { match: 'myapp.com', propagatorTypes: [ 'datadog' ] } ] },
06-12 11:01:51.017 28614 28724 I ReactNativeJS:   sampleRate: 100 }
06-12 11:01:51.024 28614 28725 D DD_CONFIG: { NativeMap: {"clientToken":"<READACTED>","trackingConsent":"granted","nativeLongTaskThresholdMs":200,"telemetrySampleRate":20,"applicationId":"<READACTED>","env":"prod","nativeCrashReportEnabled":true,"longTaskThresholdMs":0,"sampleRate":100,"site":"US","additionalConfig":{"_dd.source":"react-native","_dd.sdk_version":"1.6.0","_dd.native_interaction_tracking":false,"_dd.native_view_tracking":false,"_dd.first_party_hosts":[{"match":"myapp.com","propagatorTypes":["datadog"]}]},"vitalsUpdateFrequency":"AVERAGE"} }
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: Exception in native call
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: com.facebook.react.bridge.NoSuchKeyException: trackFrustrations
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:117)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:149)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.datadog.reactnative.DdSdkConfigurationExtKt.asDdSdkConfiguration(DdSdkConfigurationExt.kt:27)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.datadog.reactnative.DdSdk.initialize(DdSdk.kt:63)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.jni.NativeRunnable.run(Native Method)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at android.os.Looper.loopOnce(Looper.java:201)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:288)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
06-12 11:01:51.026 28614 28725 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by louiszawadzki** [comment]
Hi @short-dsb, thanks for your answer!
This looks very strange, it's as if the `trackFrustrations` parameters was removed when passed on to the native side. I can also see that the `configurationForTelemetry` is also not present in the native side as well.

It could be something very specific to your case, could you reach out to [our support team](https://www.datadoghq.com/support/) so we can exchange safely around the specifics of your project?

Thanks a lot!

**Comment by short-dsb** [comment]
Not seeing this issue in v1.8.0; it appears to be fixed.

Thanks for looking into it!
