### ISSUE TITLE
Android Device crash happened on first time app launch.

### ISSUE THREAD

**Issue by bgrajesh57** [DataDog/dd-sdk-reactnative#618]
### Stack trace

Crash happening on Real Android device only at very first time app launch.  

We also used code push integration : [https://github.com/microsoft/react-native-code-push](url)

Please let me know if any more clarification needed

React native SDK Details:

    "@datadog/mobile-react-native": "^1.8.5",
    "@datadog/mobile-react-navigation": "^1.8.5",

Crash logs:

```
com.facebook.react.bridge.NoSuchKeyException: nativeLongTaskThresholdMs

at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:117)
at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:154)
at com.datadog.reactnative.DdSdkConfigurationExtKt.asDdSdkConfiguration(DdSdkConfigurationExt.kt:20)
at com.datadog.reactnative.DdSdkImplementation.initialize(DdSdkImplementation.kt:56)
at com.datadog.reactnative.DdSdk.initialize(DdSdk.kt:30)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:219)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)

```
![Screenshot 2024-02-22 at 13 30 47](https://github.com/DataDog/dd-sdk-reactnative/assets/132445927/6fe78e29-b79e-4a51-91b7-3f5835b3c675)

### Volume

50

### Affected SDK versions

1.8.5

### Latest working SDK version

not sure

### Does the crash manifest in the latest SDK version?

Yes

### React Native Version

0.71

### Device Information

All android device

**Comment by louiszawadzki** [comment]
Hi @bgrajesh57, thanks for reaching out!

Did you recently update the version of the SDK?
The error message you are sharing could mean that the native layer of your app is indeed running `@datadog/mobile-react-native` version `1.8.5` but the javascript layer is running an older version.

This could be the case if you upgraded the SDK but didn't bump the version number of your app. In this case, codepush bundles still using the older version of the SDK could be used on the JS side, which could explain the issue.

You should be able to fix this by either bumping the version of your app or removing old bundles on codepush.

Let me know if that solves your issue!

**Comment by bgrajesh57** [comment]
Hi @louiszawadzki I didn't update datadog sdk recently also we are using code push lib version is
 ``` 
react-native-code-push": "8.1.0"

```
Should i required to update latest version  ?

https://github.com/DataDog/dd-sdk-reactnative/releases/tag/2.1.1

I have bump app version when app installed I can see latest bundle. the problem is very first time app install its crashed 

let me know  any other thoughts

Thanks

**Comment by louiszawadzki** [comment]
@bgrajesh57 thanks for clarifying this!

Could you share how you initialize the SDK? 
Can you also share if any change was made to the configuration in one of the codepush bundles?
Does any particular change seems to have triggered this issue?


Thanks a lot :)

**Comment by bgrajesh57** [comment]
Hi @louiszawadzki  Thanks for the inputs, 

Something we have to do with code push implementation form our end. so closing this.

Many thanks !!!
