### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by joekabogo** [DataDog/dd-sdk-reactnative#658]
### Stack trace

Fatal Exception: java.lang.NoSuchMethodError: No static method isInitialized()Z in class Landroidx/work/c0; or its super classes (declaration of 'androidx.work.c0' appears in base.apk)
       at com.datadog.android.core.internal.lifecycle.ProcessLifecycleCallback.onStarted(ProcessLifecycleCallback.kt:27)
       at com.datadog.android.core.internal.lifecycle.ProcessLifecycleMonitor.onActivityStarted(ProcessLifecycleMonitor.kt:40)
       at android.app.Application.dispatchActivityStarted(Application.java:413)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1482)
       at android.app.Activity.onStart(Activity.java:2016)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:496)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
       at android.app.Activity.performStart(Activity.java:8570)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
       at android.app.servertransaction.StartActivityItem.execute(StartActivityItem.java:43)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8395)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Reproduction steps

it just crashes randomly in production

### Volume

4%

### Affected SDK versions

2.3.1

### Latest working SDK version

none. we have been seeing it more often recently.

### Does the crash manifest in the latest SDK version?

Yes

### React Native Version

0.73.6

### Device Information

Samsung -50 %
Xiami-20%

**Comment by marco-saia-datadog** [comment]
Hi @joekabogo, thank you for reaching out!

The problem is caused by conflicting versions of the Android dependency `androidx.work:work-runtime`.

You surely have another dependency in your project which is pulling a version of `androidx.work:work-runtime` which is not compatible with ours (`2.8.1`).

Can you please show us your dependency tree? You can run:

```sh
cd android
./gradlew :app:dependencies
```

**Comment by joekabogo** [comment]
thank you @marco-saia-datadog . i will apply the fix
